use std::collections::HashMap;

impl Solution {
    pub fn word_subsets(a: Vec<String>, b: Vec<String>) -> Vec<String> {
        let mut results = vec![];
        let array = a.clone();
        let docs: Vec<HashMap<char, usize>> = a.into_iter().fold(vec![], |mut acc, s| {
            let mut map: HashMap<char, usize> = HashMap::new();
            for c in s.chars() {
                *map.entry(c).or_insert(0) += 1;
            }
            acc.push(map);
            acc
        });
        let query: HashMap<char, usize> = b.into_iter().fold(HashMap::new(), |mut acc, s| {
            let mut map: HashMap<char, usize> = HashMap::new();
            for c in s.chars() {
                *map.entry(c).or_insert(0) += 1;
            }
            for (key, value) in map.iter_mut() {
                let v = acc.entry(*key).or_insert(0);
                *v = *v.max(value);
            }
            acc
        });
        for (i, doc) in docs.iter().enumerate() {
            let mut matched = true;
            for (k, v) in query.iter() {
                if let Some(value) = doc.get(&k) {
                    if v > value {
                        matched = false;
                        break;
                    }
                } else {
                    matched = false;
                    break;
                }
            }
            if matched {
                results.push(array[i].clone());
            }
        }
        results
    }
}

struct Solution;

fn strings(a: Vec<&str>) -> Vec<String> {
    a.iter().map(|s| s.to_string()).collect()
}

fn main() {
    println!(
        "{:?}",
        Solution::word_subsets(
            strings(vec!["amazon", "apple", "facebook", "google", "leetcode"]),
            strings(vec!["e", "o"])
        )
    );
    println!(
        "{:?}",
        Solution::word_subsets(
            strings(vec!["amazon", "apple", "facebook", "google", "leetcode"]),
            strings(vec!["e", "oo"])
        )
    );
    println!(
        "{:?}",
        Solution::word_subsets(
            strings(vec![
                "eonsczsuio",
                "pdqjcmrfxz",
                "loszivaufo",
                "rbnkwsvyhx",
                "kpufkcxyeq",
                "lyjdhotyel",
                "imdozuorso",
                "ovlqbsvssp",
                "ozuhievhos",
                "souoqgujzi",
                "oplnrbpobh",
                "xjzitohsou",
                "jpqlmtpjlg",
                "kcdbfklgio",
                "xpebgcrbaw",
                "livbtmpzuh",
                "wtkpwxodby",
                "riydijdhwj",
                "uozsuopniu",
                "qpuvmmxstc",
                "yijuogljic",
                "spvykbnvvi",
                "yocrzuosui",
                "siuzzjiyoo",
                "pdbbztjftl",
                "uxszimooks",
                "ghxrfwmbue",
                "mmpocqhudi",
                "oizqosuwsb",
                "xodpyuglkr",
                "emlnwpaqei",
                "olsoiqtuzp",
                "rvetlcqssg",
                "wosozitswu",
                "giuohfozsl",
                "wfbfhyjmig",
                "muxqrpxdgx",
                "xcykwgqydk",
                "mcktglwpfl",
                "rzisbouomc",
                "ootikzubsv",
                "iyozouzsou",
                "gboadqunyy",
                "ssoobduidz",
                "jsniolguoz",
                "ttjuadftbo",
                "bqgxindxjp",
                "tcfjxuvmte",
                "lxgrzeyhxp",
                "zmoisuuyfo",
                "iuoszcktjo",
                "ibsodbozuo",
                "yukuftzzal",
                "wwdkeiadbg",
                "owlftdjowr",
                "uqimziroos",
                "oscukzuwio",
                "mpgzfsvjbi",
                "zpqsrtlyfw",
                "zwduoiobfs",
                "jhagzsooiu",
                "izmojposub",
                "jspolbohxc",
                "keczmrbmht",
                "cuwlsoozei",
                "sbxoiqvuzo",
                "ogizuiblso",
                "jziozsueoh",
                "tsmvcbqugr",
                "lxudtegjsm",
                "cpusywhvnu",
                "uisozyhwxo",
                "uuoswiogzn",
                "wpzecgbvkv",
                "rzycouomis",
                "ouizmospco",
                "cbbzsooyul",
                "dxwhrzozly",
                "yoiosxzsuu",
                "pzbphoiuos",
                "ipdlwbpvgw",
                "cmbxphxmai",
                "zukisadoos",
                "zoisowuxxf",
                "unexqvqxwr",
                "zeppoatjng",
                "yidbbiplne",
                "ioifbiujmf",
                "roouhxizse",
                "eutziocbos",
                "ioocqmnusz",
                "sizonujoeq",
                "usikmqgsuq",
                "oouzisrjlc",
                "wiiiubosoz",
                "mitsebhrgh",
                "ijuzouojsf",
                "gxnqwsyrkc",
                "skilouzzog",
                "ooyfaichac",
                "buwobkophd",
                "usooizvgku",
                "xdljecjdvf",
                "yogcpfykur",
                "qizobepous",
                "ozusrfokio",
                "rnmypbiefy",
                "oistzouzrz",
                "ghswkkfwcq",
                "rissiycobi",
                "roizdsuhdo",
                "wuljogxllu",
                "soiszokurj",
                "poulzsioud",
                "mkimxrrtwd",
                "ooqaezxusi",
                "yhzvvngdvr",
                "oznuoixrsl",
                "ondzismuov",
                "nleqnzzpze",
                "nuszrodooi",
                "ibrnngsaws",
                "gvjlfzywmj",
                "ieyxnvbdml",
                "vcsqaomqqd",
                "hboizsuigo",
                "ytoazuiots",
                "uzjsooiykd",
                "omuimoszqo",
                "iumwszosno",
                "jmezhfqlbg",
                "efqclhyijm",
                "zrbgeqbqxm",
                "ciqhtudrih",
                "pbjexqhduh",
                "juilclzoso",
                "aqlcmwdmhk",
                "iazuogoels",
                "jouizqsooo",
                "lqhtvbglbv",
                "maharvczvc",
                "ntuiozzsro",
                "oloshucgiz",
                "uosuijoznv",
                "oouuzhsori",
                "narflxvcma",
                "uzipnooycs",
                "oifoaasyuz",
                "snlooizjud",
                "jggnvdtguj",
                "cpozdtoisu",
                "wybinspusu",
                "qigsuaoobz",
                "wmwvvarkvz",
                "yqpcljgsmt",
                "ylhdtsxcds",
                "awyywnmrjo",
                "iouktozosm",
                "sowzuihtoo",
                "oswzkdyoui",
                "ynnrzflqkt",
                "nupvwfrimt",
                "dgnejksdru",
                "dlzphjzegv",
                "hjumyhphxf",
                "uuwobziocs",
                "dkglfwxvxe",
                "zaofcoosui",
                "iszouchjoo",
                "vginuobszo",
                "uozosrqeiq",
                "zysiuzboao",
                "szifzvooou",
                "uzdkioujos",
                "jiofzmuaso",
                "viwowwmidb",
                "eozefsoiou",
                "mkqhfrbnlr",
                "jqiuoruszo",
                "yaopcmwulb",
                "vykopngiuh",
                "sytosedcnh",
                "uuiuslzowo",
                "vjlenievap",
                "oasuzoiujh",
                "vzoieusosx",
                "iovozuuqst",
                "mdsizrzoou",
                "zosgiqlouu",
                "zimubsoohs",
                "njhtcxsfoy",
                "zfzoivzuos",
                "siozdoxurl",
                "oopsijzukf",
                "szalofduio",
                "ouodrrzsui",
                "ivdksevuxk",
                "uyuvdcnbch",
                "ptagtcdazr",
                "uzklvooiss",
                "vodcoeffrq",
                "euaztoruti",
                "bytzkefoas",
                "iqvhdnedwa",
                "qfiuzkosdo",
                "uouzsisaol",
                "invongnqne",
                "losoikzknu",
                "kwyljirmxk",
                "hzzsofuiok",
                "uzoswvoigp",
                "vovxahrpht",
                "zjzoufosiz",
                "mkciueagjd",
                "yqszrioosu",
                "xzfmcghrfr",
                "ulhooszqiz",
                "vhpwmfjogj",
                "adhemgaepq",
                "sgioansuzo",
                "oupsoczkfi",
                "fhhpgryqae",
                "niubbfcaac",
                "gaqsoymdpo",
                "ulsioozoiz",
                "oiszqoixmu",
                "vxbmomgsec",
                "dsuiowoqhz",
                "bdsrwxltws",
                "tndycinqdj",
                "yezkwplkxf",
                "szooioounu",
                "rosoozaium",
                "uwooszjiim",
                "hqiidzasqy",
                "iosopushxz",
                "uknwsqvtbe",
                "qjyuzxxwyc",
                "fxczugccvn",
                "cpruvzjvhn",
                "utazaqbsuv",
                "moiuunszot",
                "hqfouzrylh",
                "xrrkdadafi",
                "youyucujxo",
                "otspjuozwi",
                "icooabpevx",
                "cnnkojkzwq",
                "rqkzgsgltr",
                "wzhjvkzeue",
                "jfgqvzilub",
                "gumpkiqqrg",
                "lbycakxpiz",
                "cncujxrrns",
                "mgradxxlqz",
                "efzkhydjgb",
                "zziztoosuh",
                "biuszoolro",
                "wpufaibxjn",
                "yitilgivft",
                "oaamimtrkw",
                "ejceebkxfb",
                "wllcffqjmy",
                "sooumbzuti",
                "riouqzoscn",
                "catjvopmen",
                "ftkuzsosio",
                "muzhqsoooi",
                "krnyxicckz",
                "grzazrplhy",
                "qdvftafepn",
                "janwnbzpyo",
                "fqokbehynu",
                "sooguogzio",
                "pdowfqgmpc",
                "tkyqleuqfd",
                "dxnsualmbi",
                "sulzglomio",
                "eewgxrmrwj",
                "siivoukozo",
                "xzooiyeslu",
                "sryvdqdmzt",
                "csaswuoopu",
                "nuwqmmqmgm",
                "jagzfjyqil",
                "gisuxkpzoo",
                "ysizpouhoy",
                "bhtaiosouz",
                "ghkawipywc",
                "iuokgzsooh",
                "kozluoiskn",
                "xstvfetbrd",
                "hypngksnvo",
                "dishoohuzu",
                "jztoviurpn",
                "uozsoitiov",
                "eiksasymzu",
                "zzeosuokip",
                "rhsjkestgc",
                "zuoicozeos",
                "vfftrjlsgq",
                "clemxnnnsu",
                "unisqoyzom",
                "sdseomnbsn",
                "imrhiclfvj",
                "uocolsysiz",
                "optnjnyyfn",
                "avhkhpeedn",
                "zjilcspqfb",
                "psozobvuiz",
                "husscouizo",
                "ouspomfkzi",
                "kxrsfdssej",
                "sgzuxcoiox",
                "toizsxoqou",
                "ozcvlflqud",
                "mwdvuynzwt",
                "gzfyywfleg",
                "gflqyjdlrv",
                "bciekddsmj",
                "suozzoiilc",
                "mvkhbbnuxt",
                "hhpazsrkgl",
                "shtufvtncf",
                "nxphmhmjog",
                "rsjfmecfua",
                "iyyembxloe",
                "owzxomiusx",
                "ndvcprpgst",
                "iuxstgchzt",
                "qnxanvujhm",
                "beucsycvyb",
                "igzoouiqks",
                "znfkqpxjti",
                "egbwrawfid",
                "njgssdchow",
                "wqajjhfbum",
                "fuzlhdznpx",
                "wwemxzrveq",
                "xqlgegfijb",
                "vdjpvyavuw",
                "uiihozooas",
                "uvzouooibs",
                "ivotoguzsb",
                "opiimuosgz",
                "oswikouzgo",
                "soiiuoitzr",
                "isoofzlmug",
                "lrngejwxoq",
                "oiaszdcoou",
                "rnvlhubwpu",
                "jxdlbuihsq",
                "nbattycbfo",
                "zuoimsuoft",
                "cumwkpsqkf",
                "jisboyfuoz",
                "duuhiuosoz",
                "siauzoxozp",
                "vmzkqyvjoe",
                "auhzdfvbrm",
                "xgcfketiai",
                "doiszmofuu",
                "bhkhsbkzxa",
                "osbuzwovin",
                "yoczosizfu",
                "udoiaxozas",
                "dziuouzvso",
                "ojzfsgouuj",
                "kolulwnmkw",
                "sfaiqogqqv",
                "otfuzismio",
                "zsffslybgi",
                "izfoiunost",
                "rkwzhgkyro",
                "wfguozsiuo",
                "onhipizroy",
                "zjlcyogjkc",
                "zsdwjttdtw",
                "xbmrpxylsw",
                "mnauknqtua",
                "nuqszoinom",
                "oozcksgziu",
                "aormkvpuix",
                "suiohxozre",
                "viluozskon",
                "yclbwrqvbe",
                "tbqunbltiu",
                "wosouyzfii",
                "bnnbjczltv",
                "oswiqbfuoz",
                "irtnhxetcm",
                "gunizoduso",
                "dzpzbyiggh",
                "dolmiszoou",
                "fkwzkavxfj",
                "vubhmeeevb",
                "iftopcdjkh",
                "ufdgzlzwpf",
                "wboooqsuiz",
                "xozxtugois",
                "ynisliouoz",
                "iuuosozdsk",
                "lqmvywbkfz",
                "oiuozpesdl",
                "favexnzmvy",
                "wooqisgcuz",
                "gocziysuro",
                "xqovmjiibs",
                "pozoxiuxsx",
                "lhdidsydbe",
                "oiisoxzuky",
                "soiwzscoub",
                "uioojisztu",
                "hoisukzfno",
                "oslkziolsu",
                "ijmomoucsz",
                "aqgsoiouwz",
                "jycjwnsdea",
                "dusbnhkwdm",
                "ifoozskoui",
                "eokewbinjz",
                "trxqgqelcd",
                "zsoirmokou",
                "yppfceppew",
                "fxitfkuwdc",
                "iqpozousdp",
                "vxxvbebyob",
                "mlozscifuo",
                "iuouuoszun",
                "zseuuziook",
                "sdjpsudvus",
                "ocsniuttzo",
                "wyszumbwac",
                "jnxqnuwasf",
                "mtdojqhrhp",
                "ioedidnndo",
                "enpcstsmiz",
                "wjlyrmypap",
                "aswfprmoou",
                "uioscbxmoz",
                "fgxznnfgjg",
                "ksuiolozof",
                "hkbvfvqvdx",
                "yasduozoiz",
                "zcsiuzoosr",
                "hdnohyktzs",
                "vocxzfxxxc",
                "ouszhimoxs",
                "uooniyuizs",
                "chuafnwaay",
                "deitajarjg",
                "irnsozukzo",
                "akgxnsfcsv",
                "iszuxbogos",
                "zuihgeouos",
                "ouiuzzorvs",
                "koouiwwsuz",
                "mhfxcwscnu",
                "bclledjhja",
                "zztuogfiso",
                "wwceoelmfm",
                "szouihuozi",
                "lsnqoiovzu",
                "gnrrulenac",
                "oaiousrfzq",
                "cpkwvqqyfi",
                "siouobzcam",
                "fsiooybuzp",
                "ujlaymjbfr",
                "qxsrvctjjt",
                "jidpfksaqr",
                "zuwboiosxo",
                "sloooanizu",
                "tkojgbxaby",
                "izeozpuios",
                "rozisgvzuo",
                "skqbbngaax",
                "eosuiozszm",
                "tanaomdzlb",
                "rzocgecpnu",
                "ipupizsoso",
                "zojtuwhsio",
                "oouilhskqz",
                "slqpezjehd",
                "oryuzsziso",
                "nkdpcfyzio",
                "irdhfrynis",
                "zapaimbgqs",
                "doqiobsouz",
                "dzcsjlusuo",
                "uzmocosqio",
                "ofrvpacdfz",
                "spiraocbqq",
                "letwpopcan",
                "hrrxecchnl",
                "suoazozqui",
                "osviyonouz",
                "oztcotvfls",
                "zguifsboeo",
                "fkjlewrpnf",
                "cpudxkzryp",
                "wlzmousoip",
                "zyosioouvk",
                "ucepwiyilc",
                "ofiisuznor",
                "iooualajzs",
                "omvubajirj",
                "qdejrgguir",
                "zjuewboois",
                "ueassvnine",
                "uyflbbstsn",
                "ohouaazisf",
                "iszocunllo",
                "uwmkjikbhq",
                "azabuepspw",
                "kjcoovphpy",
                "eqptppjxff",
                "feifdxtolp",
                "zfojiusvoc",
                "oodiuzzqts",
                "whnaysoucl",
                "strmtgehrc",
                "wgzykhqryq",
                "ioudsoxzpo",
                "zucuioshto",
                "wybtxvnvxr",
                "ziubywsoxo",
                "muglbyncyn",
                "uikrosoziu",
                "iozstocuzw",
                "ywolfimhky",
                "cxbzjlgfgy",
                "ozsyiouypf",
                "okjsvwdpka",
                "josoiuzhtv",
                "jphpcsnzjy",
                "tktepyxdxi",
                "dmisegqskr",
                "tyusiqzooo",
                "dxitrupbvp",
                "ewnqfpkycf",
                "obuzoosiec",
                "ozuvioeizs",
                "inszonuohs",
                "fooiizupru",
                "izduaoobcs",
                "sueozioumy",
                "mwlygyocuo",
                "tzaasoshkr",
                "zdueuvkhhs",
                "urpwycypat",
                "piiwofcijc",
                "hnxtsvluqf",
                "twoiusemoz",
                "aasxoiuzzo",
                "xrgamlauim",
                "uobsilomzt",
                "bluuiazoso",
                "ubdhfnhufd",
                "oszwurcoij",
                "uzniosodrw",
                "xuxerboqan",
                "souoicodzf",
                "wvqaawwtny",
                "zgoceosiuj",
                "dtqbllaonc",
                "gkukqvuinu",
                "ozjbzosinu",
                "osuzhlonpi",
                "oluzslieov",
                "cduoszquio",
                "obswziousx",
                "ijozoufacs",
                "oovizcdsiu",
                "dfrsuuiupn",
                "hlciqwiodz",
                "befjeeehvg",
                "zzojsiaudo",
                "uigvdoposz",
                "odvsioodzu",
                "fesqehlape",
                "ewikldjqpz",
                "inosjxozug",
                "rgfucoatwu",
                "spyhnbezdq",
                "iuxqwlqruv",
                "vzlexcubdv",
                "watbufguhw",
                "oosxubginz",
                "uziorpscwo",
                "qcpplztqba",
                "pdbxwflziq",
                "puygrphixi",
                "sjozoziguj",
                "iuoqzuossm",
                "zooiluuwse",
                "ilzoosoriu",
                "soiznuioss",
                "twyurdtupm",
                "pdeiacbkdx",
                "lsyickouoz",
                "awzysooiuu",
                "fdlxjofdls",
                "uzloiospsi",
                "xqvweouwee",
                "lviuozsojy",
                "ofksizobuo",
                "wvusqfdjmg",
                "vouzoosius",
                "urubhwrbrh",
                "uzjimsogoj",
                "qsujhoizoz",
                "sskuoszlio",
                "guluoiqszo",
                "mjnhairnjm",
                "dmbodnvluo",
                "hbdkuliara",
                "nuoszsrioy",
                "siogzogufp",
                "vrjohygksl",
                "tewzyxwyta",
                "inrxrbnbrm",
                "caumfooisz",
                "xidchtbtsp",
                "zoipugsoho",
                "chhszzrzuu",
                "uicmsziouo",
                "oicwuvozgs",
                "douozizstb",
                "irfodtprcf",
                "aqhcvwmvrb",
                "eizsvwoyuo",
                "uojoaoispz",
                "osvonzixug",
                "cisouzoyus",
                "wkqnzvhsee",
                "aljqjjagpp",
                "lflovuoisz",
                "oziorzsuzs",
                "oseyioiqam",
                "ppxflmxmkv",
                "jgksopslfy",
                "iomozaqsua",
                "lusgowiozi",
                "wrojdlzgix",
                "dmqzdzrmgx",
                "kpeuzjqijt",
                "zisvoshiuo",
                "iezsoiuosd",
                "axhysgebdj",
                "scitzykouo",
                "ioczuzosqz",
                "uzomvizsou",
                "suzooviwsq",
                "uolszsoriy",
                "rnjsegzwoo",
                "opiuszobmw",
                "rurhmaboxr",
                "souzzsiost",
                "xkaivqqpzq",
                "ihfmotemzf",
                "kionobuszq",
                "cvbeodplyb",
                "sueoirzyxo",
                "eqzzlreakg",
                "ootejizuso",
                "ikyhgdqdjq",
                "szwuoyjibo",
                "enrxsygsie",
                "oosygkhuiz",
                "jogyfliwey",
                "pqooumuzis",
                "buvcgsoozi",
                "mlsvmovjok",
                "aplcyvmboq",
                "osqozvimnu",
                "irqngzoous",
                "izuozwcios",
                "zhrospiosu",
                "gozslokiux",
                "izsuooulzr",
                "ijiusolfzo",
                "txxmraczey",
                "zmsuoqoial",
                "cuzoiszqoh",
                "ovcvpcfprn",
                "pjscarepoa",
                "eoqqoismuz",
                "ikoyozsudo",
                "sowznozubi",
                "obuikwozls",
                "piiovodszu",
                "ukjwothgme",
                "tqqbusrbaw",
                "wfoiusbouz",
                "oiojxzitus",
                "shozoouydi",
                "uksiconolz",
                "shtgvujbtb",
                "kzoioposyu",
                "tivthcyaqq",
                "uixuzisook",
                "terjnyeekr",
                "erwszoiouu",
                "zuowokzusi",
                "ncdizastwu",
                "sksnpaqetj",
                "rbshxmvzav",
                "seipozyuow",
                "oqsouuznoi",
                "edfffqbvhe",
                "ooignzruys",
                "uqoomsezim",
                "ioowusnpzj",
                "aozkuqgiso",
                "xhrnjedkgr",
                "iqhjaqshoa",
                "ucybhiczsq",
                "diouozizst",
                "lnoomepukz",
                "rvbutrofau",
                "ozuasuwioi",
                "jyylzkvvpo",
                "ooiionuszz",
                "swrooquizs",
                "qtqummhrnd",
                "jupfmtqltz",
                "nhxfiiuagp",
                "qqblvqhjdd",
                "ittymnjion",
                "lbxbbiikls",
                "plcgllnljy",
                "flxemcbwpx",
                "rcxbdcykxk",
                "ltxjmuckvl",
                "vtpfeivyoa",
                "ufszojvoio",
                "oiuleoozms",
                "iajkjimlbx",
                "lwumarzpnz",
                "iqsuvvcooz",
                "zosyuairoj",
                "zzosuoupit",
                "znldisoruo",
                "oslituozyz",
                "suzbkoiiog",
                "ukaoztsoci",
                "yoqczoiswu",
                "wuszoiouol",
                "yoziuohbzs",
                "hueuwocmlt",
                "oszoizuosi",
                "qsfoizuioh",
                "zsuaogozir",
                "frlisiykej",
                "pzumroosiy",
                "huikdaqwtj",
                "pxqklznhos",
                "nztztdjivd",
                "csfacjnvgo",
                "oqozinavsu",
                "erildxablo",
                "oozskewgiu",
                "sjwkomyhlc",
                "dowoiqgklk",
                "xlmynpcyor",
                "lomfqtqxlh",
                "pzodumioas",
                "usxziyywoo",
                "wfokkinsnq",
                "pqtnrmadrb",
                "odujiiozsa",
                "isoouyzoia",
                "eozlxazimz",
                "jrpzfdiinh",
                "ndoobeyrfi",
                "bufcievtyi",
                "cqassrxotg",
                "onmswuiozi",
                "bouispoxez",
                "zbwuqevofr",
                "zuloxqieso",
                "xoolihzqus",
                "nbliqeiwmx",
                "zuvoiooegs",
                "pomznisuao",
                "iworknmqkq",
                "sioosozsku",
                "smnhxhutul",
                "nqrcamzxlb",
                "ozmsjivuom",
                "zkxotdxngw",
                "huttmgowtp",
                "oszjuzsioz",
                "nskcuewkec",
                "isuododupz",
                "cgocacctvw",
                "xousqlzohi",
                "mjgrchwrsj",
                "dmierlwftn",
                "zsqzuuoqoi",
                "ldizpczglv",
                "wvuobsidoz",
                "yzoasuuoiv",
                "zaoicqoous",
                "sgyoouikzz",
                "siztqxobuo",
                "oodvzsusij",
                "zimluxuoso",
                "quwbxflrrh",
                "pooiuxesvz",
                "dkhqtiavak",
                "fihlhusaqr",
                "qzhooistui",
                "ccusjimzoo",
                "sszozuvoai",
                "zhpfxskeom",
                "zogrrkwjoe",
                "zmouqizlso",
                "zxdsnouqio",
                "ioguucizos",
                "kpczxvycgb",
                "ivieyuqlvn",
                "ttomziuzso",
                "firroowqbm",
                "nosuwizdop",
                "vcokkqdeyf",
                "gppcldmpne",
                "rfsuozioza",
                "sitlmquseh",
                "sjmoibhzuo",
                "fumrdhzwwk",
                "ziuxsoizoe",
                "bykhozjina",
                "fnufnbebkm",
                "oosaiuuzvk",
                "fzsuouxioi",
                "xuekxpqvks",
                "rjqeihcbhn",
                "izizoesuoy",
                "ortouiezus",
                "osiobrzoug",
                "sqpohuziuo",
                "udiocozcss",
                "udsqkneuzo",
                "ousgcziouy",
                "rhixjizbeu",
                "ifuosdkozu",
                "relpevefao",
                "soazueuxoi",
                "saooizsuvz",
                "hoosziugon",
                "sbauuoiozy",
                "ukgbukjxzd",
                "qzfdarvkdf",
                "upmdpejjyy",
                "toksosabux",
                "tsleoigvso",
                "yoosueyipz",
                "icbstomkfb",
                "puzfjtdpxt",
                "aoyoskuzui",
                "oogcvgjbpm",
                "jaoiuzosms",
                "ozwustiqob",
                "vrsdkkgbor",
                "fbwvmxygbj",
                "jisqsouboz",
                "oizgruoios",
                "odmmadkscf",
                "otopswuuiz",
                "qblzxosuoi",
                "dflihtdluq",
                "duvqemwtze",
                "byosuwhioz",
                "ssefzouomi",
                "cdjisxdcea",
                "oruersiosz",
                "osouwozios",
                "sibuodpmzo",
                "mtrsvpmafw",
                "fvkatmbhlp",
                "tzvssuoixo",
                "qioursdzmo",
                "zomszifrou",
                "uiyswzoovj",
                "owtiodmsuz",
                "xomaayewdw",
                "nkxugrsxcs",
                "qwvirgwsxn",
                "hatjdmkbuw",
                "zgincazlyu",
                "muvgxwcvev",
                "siievouzoh",
                "hvtlphksdg",
                "kisvzooukq",
                "vzosoifucc",
                "oigsqoqsuz",
                "xzouosuijk",
                "ioeoooufzs",
                "ftoeodfzoh",
                "niolzsauop",
                "tbaotfmgzt",
                "nvifwbgeez",
                "eauuvrnwid",
                "gozyhtkpxm",
                "ocziiausuo",
                "ozutwomsii",
                "uozsxbxixo",
                "cauezhyyuk",
                "zasoniiosu",
                "etjwgzmydh",
                "xsuwoozijo",
                "gamzsmohxj",
                "iovhiouszk",
                "hizwusoosf",
                "nzmusoolip",
                "qmrosbiuzo",
                "spooszicuo",
                "zuisiiordo",
                "ewiuozlosi",
                "zspuligoou",
                "xvoupntxzn",
                "mtussonioz",
                "rulfgkycfa",
                "deorgxxkka",
                "uuzaioyosi",
                "oziuosyeto",
                "lkrivgdtsc",
                "oyoizpsuwo",
                "pooiaxtsuz",
                "duzeiooszv",
                "khhhgxerxd",
                "qwbdgmqury",
                "hzoudoesiq",
                "siziawuooj",
                "vmsbnbchhx",
                "supuoozvib",
                "suzuigcoox",
                "agxgxdevtw",
                "mokxnwyglx",
                "qiaupwlsmv",
                "uszokxioey",
                "ixyuqlkrpu",
                "sooiciujlz",
                "mzbouicogs",
                "bsiuozouth",
                "nyarzlxhqj",
                "ptqanvqqtf",
                "luzuizsoeo",
                "ishzoouhzs",
                "hohfhwznuc",
                "kaljtvgsme",
                "qzoihosutg",
                "pamolxwmxg",
                "tzfcokdwin",
                "ziwohousbz",
                "xqzvfcqwcz",
                "ojezoislpu",
                "uooaizosui",
                "zgmzjnxjtu",
                "osuioieizq",
                "aospseblhb",
                "omynzuusoi",
                "soayfzouix",
                "plofnexttd",
                "obsiwzuyof",
                "yosoqviwzu",
                "dhomuwimtg",
                "qgtykkwmjx",
                "oucxfzoisk",
                "cihgsazvsj",
                "odwxelicbd",
                "budtkxdvxp",
                "cioxzosisu",
                "kxusqvcyln",
                "jscipzhetu",
                "sfojdytnqy",
                "zjpagexvuj",
                "iozuonrsfr",
                "oxszriolhu",
                "ugozijpohs",
                "wqznpputre",
                "mpyuunlecu",
                "ymsasizouo",
                "yknrnyhdhr",
                "oukoputizs",
                "psqouozjni",
                "tziposopbu",
                "njsnqvbepq",
                "qotqazuois",
                "kptosdjrxq",
                "tifoyguwhz",
                "szsuycioho",
                "hhbelsglqc",
                "pthxgkbwla",
                "waaohzkyma",
                "idokcyjvzn",
                "zvsozuiwoa",
                "ruaiodsozn"
            ]),
            strings(vec![
                "uoszo", "osou", "o", "u", "zuo", "oszui", "osuzo", "suo", "io", "sizou", "uosi",
                "zi", "iosuo", "ouoz", "ioos", "oz", "iz", "s", "soz", "ouizs", "zs", "osuzo",
                "suoio", "o", "souzi", "oiu", "usi", "u", "o", "u", "usz", "ousoi", "osu", "osiu",
                "oso", "io", "zsuo", "io", "i", "z", "sooi", "uzsoo", "us", "soizu", "ouzs", "u",
                "oisu", "izuo", "ou", "ouoi", "oisuz", "zos", "oiu", "suooi", "ozu", "zoui", "ioo",
                "z", "isz", "s", "ousiz", "izo", "z", "s", "soo", "oio", "so", "s", "u", "o", "o",
                "sooz", "oozi", "oo", "ioz", "u", "oi", "ou", "io", "uzoi", "uoso", "oz", "oozi",
                "zoso", "o", "zsoui", "uz", "soi", "o", "usz", "zuioo", "osz", "si", "iosou", "iz",
                "zso", "ouz", "uoso", "osouz", "uzi", "osio", "os", "i", "so", "sozu", "isoo",
                "uoz", "uo", "o", "iuso", "iozs", "zios", "s", "si", "ooi", "ouzs", "ouzoi", "is",
                "o", "z", "oo", "izuo", "ious", "oszi", "uioo", "so", "s", "izo", "osoz", "o",
                "osz", "uo", "zsu", "ous", "souzo", "ioso", "oi", "z", "uoos", "zi", "o", "osziu",
                "s", "uzsi", "iozus", "o", "oioz", "os", "u", "ooz", "o", "z", "o", "oo", "o",
                "zsuo", "zsioo", "ouo", "zoi", "ouio", "o", "ioz", "o", "ozo", "o", "uo", "zi",
                "osozi", "so", "zo", "iu", "szio", "sozo", "s", "io", "o", "z", "ozu", "izo",
                "osz", "usz", "uz", "oius", "oizou", "suoiz", "soo", "io", "soozi", "o", "uiso",
                "suo", "z", "oszou", "zois", "oos", "zuooi", "u", "oozu", "so", "u", "uizs", "iu",
                "ioso", "oo", "osouz", "io", "o", "u", "usz", "uo", "suooi", "ozoui", "s", "zooi",
                "oizso", "zouis", "o", "zos", "zoo", "zosou", "zsuoi", "u", "u", "zisou", "uzio",
                "ozs", "oisuz", "o", "os", "souio", "zs", "ioozs", "ius", "suozo", "ouoi", "uooz",
                "sio", "osi", "zosu", "ous", "siz", "zsio", "ioozu", "zisou", "soo", "iosu", "oz",
                "soouz", "oiu", "uos", "osu", "zoou", "oziou", "ioo", "osizo", "oouz", "iuosz",
                "i", "z", "u", "zsioo", "zouos", "ouso", "osizo", "i", "uosz", "oso", "oiosu",
                "zoisu", "u", "suoi", "oiso", "ooi", "ozus", "oi", "zs", "ioz", "ziuo", "oiu",
                "sozui", "oi", "osuz", "uioos", "i", "iosuo", "us", "z", "oizuo", "osui", "oizou",
                "o", "ou", "s", "uz", "io", "zuo", "ios", "soi", "siuoo", "siou", "s", "osuoz",
                "uos", "os", "zsiuo", "oszoi", "szio", "zo", "z", "isu", "siz", "izuso", "ois",
                "os", "isuo", "s", "oui", "z", "oi", "usizo", "i", "uoosi", "is", "uz", "suo",
                "so", "uo", "uzio", "soiu", "usoiz", "i", "suo", "io", "uo", "iso", "uoios",
                "oszio", "uoszi", "zoos", "oziuo", "s", "osoiu", "oio", "z", "oz", "souzo", "ouoi",
                "u", "i", "oouzi", "o", "uoz", "z", "iuo", "zos", "zou", "uos", "s", "zuiso", "zo",
                "suoo", "zuooi", "uz", "ozou", "oozs", "zso", "ouo", "osuzo", "zoiou", "u", "s",
                "ui", "ios", "suzo", "izous", "i", "siozu", "ozos", "os", "i", "zusoi", "oo",
                "iuso", "izo", "oouzi", "is", "suio", "oozus", "suo", "z", "iozso", "soiz", "zu",
                "iozos", "u", "is", "siu", "uioz", "uiozo", "u", "soo", "o", "s", "si", "oiosz",
                "zu", "usoo", "uiz", "oz", "uo", "ioz", "s", "z", "suoo", "iuoos", "iz", "osz",
                "zsuoo", "ui", "isuz", "uooi", "zoi", "o", "souio", "o", "z", "ozios", "osou",
                "zui", "is", "oio", "uzoo", "oz", "uzi", "szo", "osoi", "zs", "szi", "ozus", "su",
                "uoi", "o", "isz", "iu", "uoiz", "souz", "osou", "s", "zu", "sozu", "oi", "ois",
                "izuos", "uz", "ouiz", "o", "so", "ouio", "uoiz", "zou", "uzos", "oizos", "zo",
                "i", "izuo", "uz", "ouoz", "osoui", "ous", "s", "u", "izo", "z", "suz", "s",
                "zoios", "oou", "s", "uso", "oos", "su", "sozui", "iuzso", "zo", "ou", "o", "ouso",
                "o", "s", "ziou", "ou", "zo", "oo", "o", "ouzo", "iouos", "ozui", "uzos", "oios",
                "ious", "sziuo", "oiu", "iuzso", "sooi", "so", "soo", "o", "ozui", "uozi", "s",
                "zuioo", "s", "zios", "ozu", "ozu", "uozis", "uios", "oozsu", "zo", "su", "ouso",
                "zuois", "ozsu", "os", "io", "zsuoo", "uooi", "su", "oz", "iouzo", "si", "zuios",
                "oozi", "iuo", "io", "u", "zoos", "oi", "oz", "szu", "zoio", "u", "o", "oiuoz",
                "ouo", "uz", "o", "i", "os", "os", "zoui", "uiszo", "souz", "u", "u", "zo", "ozu",
                "uzsio", "uosiz", "zso", "s", "uo", "oouzs", "uiz", "izuo", "suzo", "u", "ouso",
                "zuo", "oi", "iuozo", "suiz", "oio", "uozio", "ozis", "s", "iz", "o", "s", "os",
                "oi", "uioos", "os", "siooz", "s", "z", "zuoi", "io", "ou", "iusz", "suoo",
                "sioou", "z", "ooziu", "uioso", "i", "oozs", "oso", "ois", "uizo", "szioo", "ou",
                "o", "iosuo", "i", "siou", "z", "so", "os", "osu", "zoi", "oo", "zusoi", "ios",
                "sou", "siuzo", "zos", "zosou", "soiuz", "uzoi", "ouisz", "uosi", "s", "s", "uo",
                "usz", "su", "uzio", "oz", "osuo", "s", "sz", "oo", "zs", "sozi", "uos", "soz",
                "os", "isz", "i", "iuso", "osoiu", "uioos", "ozous", "i", "u", "oou", "ooiuz",
                "zui", "uooi", "zsooi", "iz", "u", "z", "ou", "sz", "uois", "zsoou", "u", "zu",
                "uz", "iso", "zio", "o", "zui", "ozo", "ioou", "oos", "iuso", "u", "zs", "ouoiz",
                "usz", "o", "u", "zo", "oz", "z", "u", "ou", "ios", "zsi", "iosoz", "u", "z",
                "uszoi", "us", "oosiz", "szo", "zoio", "zoou", "ouoz", "oo", "s", "s", "io",
                "zuosi", "os", "oosu", "o", "oiou", "iozu", "osiz", "szouo", "io", "uzo", "z",
                "oo", "s", "zooui", "iousz", "uoz", "sozu", "iuoz", "uoos", "i", "u", "uos", "iu",
                "u", "ious", "siz", "ioso", "uos", "z", "usiz", "soo", "zsoiu", "oisuz", "s",
                "uiozo", "z", "zo", "ois", "zo", "o", "izs", "szoou", "ioz", "s", "ozois", "oio",
                "zuoos", "z", "zsio", "zoso", "oiu", "zusoo", "oizsu", "zsou", "iz", "uoiz", "o",
                "uo", "isozu", "uio", "oui", "zi", "uiz", "siu", "o", "o", "iu", "uoo", "zosiu",
                "isou", "uz", "oozis", "zioo", "isoz", "oi", "szui", "zsu", "oz", "io", "z", "uo",
                "zuoi", "zsio", "uz", "zoou", "usi", "oou", "uo", "ou", "izso", "z", "o", "szioo",
                "soio", "zios", "iz", "uo", "uiozs", "ios", "zsuo", "osouz", "uoosz", "os", "zoiu",
                "sou", "oousz", "osiuo", "ios", "ozu", "izos", "sz", "iozou", "uiozo", "sizoo",
                "uozi", "ozs", "s", "oouz", "so", "oziuo", "is", "o", "us", "uzsoi", "uiozs",
                "osz", "iu", "oszo", "ozus", "ios", "izo", "i", "oiz", "i", "zi", "zs", "oiu",
                "osizu", "oous", "ziuos", "osu", "o", "zso", "suo", "u", "oisuo", "iz", "si",
                "szio", "i", "suizo", "o", "i", "uosoi", "s", "uzoso", "i", "uzo", "uso", "iuoos",
                "oiuzo", "szoo", "uo", "o", "uz", "uoozs", "ouoiz", "suz", "siuz", "zuso", "ooiu",
                "z", "ou", "osz", "uzioo", "zsiu", "suzio", "osiuz", "ouosi", "oso", "ou", "oo",
                "oziu", "isz", "uoio", "osziu", "zuo", "isu", "iozsu", "is", "ozo", "o", "ioz",
                "io", "uoisz", "zu", "oio", "zoiu", "s", "zi", "z", "u", "oous", "oiou", "usoz",
                "s", "zuo", "oziso", "uo", "z", "zsuoi", "ioou", "osui", "izoso", "z", "z", "uzoo",
                "uszio", "u", "z", "sozui", "suoi", "ooisu", "o", "szoio", "oz", "ozius", "o",
                "izuoo", "sio", "uz", "uos", "z", "oozi", "z", "suoo", "sz", "uo", "osioz", "i",
                "oiu", "oouis", "iuo", "sz", "oiu", "ouo", "uo", "z", "soz", "uoso", "zoiou",
                "iszuo", "u", "usoo", "iousz", "s", "ois", "szou", "zsou", "suizo", "su", "uoszo",
                "o", "zos", "iozo", "oziuo", "soui", "oius", "oi", "soozu", "zus", "i", "u",
                "uszo", "ioso", "u", "o", "i", "zioou", "ouzo", "zus", "izu", "z", "zoois", "u",
                "oiuoz", "iu", "oz", "uzsoo", "oozi", "suoio", "ioos", "i", "ouo", "zo", "zusi",
                "zooui", "si", "oos", "izoo", "izo", "szuo", "io", "uoso"
            ])
        )
    );
}
