[package]
name = "average-value-of-even-numbers-that-are-divisible-by-three"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
