[package]
name = "maximum-number-of-non-overlapping-subarrays-with-sum-equals-target"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
