[package]
name = "convert-binary-number-in-a-linked-list-to-integer"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
